# This is a workflow triggers the creation of MainWP's PHP Documentation

name: Process MainWP PHP Documentation

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ documentation ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: SSH Execute Commands
       uses: JimCronqvist/action-ssh@0.1.1
       with:
          hosts: 'root@code-reference.mainwp.com'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            rm -rf ~/Source/mainwp/
            git clone https://github.com/mainwp/mainwp.git ~/Source/mainwp
            sh ~/scripts/docproc.sh
